image: registry.gitlab.com/ecloud/ci-runners/ts:latest

variables:
  PROJECT: "component"

test_master:
  stage: test
  script:
    - npm version
    - npm install
    - npm run spec
    - npm run lint
  artifacts:
    paths:
      - node_modules
  only:
    - master@ECloud/component
    - triggers

test:
  stage: test
  script:
    - npm version
    - npm install
    - npm run spec
  except:
    - master@ECloud/component
    - triggers

